test('hello world',()=>{

})
// failed test
test('fail',()=>{
    throw Error('error in this function')
})